### ISSUE TITLE
Strange nonparametric ERF when `matched_counter` is included

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#152]
Hello! In two of my projects, I am getting wonky-looking ERFs when I include the `matched_counter` parameter in estimate_npmetric_erf(). That is, I get a smooth ERF when I run:

```
estimate_npmetric_erf(as.double(pseudo_pop$Y),
                                   as.double(pseudo_pop$w),
                                   bw_seq=seq(0.2,2,0.2),
                                   w_vals = seq(0,15,0.5),
                                   nthread = 1)
```
![ERF_main_analysis_without_counter](https://user-images.githubusercontent.com/55001348/180658891-8edd6693-ce15-4d80-b05f-6d2f21a7bd65.png)

but a jagged ERF when I run:

```
estimate_npmetric_erf(as.double(pseudo_pop$Y),
                                   as.double(pseudo_pop$w),
                                   pseudo_pop$counter,
                                   bw_seq=seq(0.2,2,0.2),
                                   w_vals = seq(0,15,0.5),
                                   nthread = 1)
```
![ERF_main_analysis_with_counter](https://user-images.githubusercontent.com/55001348/180658889-239bd77c-653f-4e0b-ad73-39df9819f88f.png)

I can maybe write a test case using the synthetic population in this package, but I was wondering if anyone knows of a quick reason or a quick fix for what I'm observing. Thank you!

**Comment by wxwx1993** [comment]
You may need to tune the hyper-parameter (bandwidth) when you fit the kernel-based non-parametric models. Also, why do you set w_val from 0 to 15, since I do not see your exposure up to 15?

**Comment by m-qin** [comment]
Oops, thanks so much for catching that! I just revised my code to go from 0 to `max(pseudo_pop$w)`. The shape of the functions remains the same, so I'll try tuning the bandwidth like you suggest.

**Comment by m-qin** [comment]
The weird spike in the matched_counter ERF persists even when I do `bw_seq=seq(0.1, 10, length.out = 15)` (and the highest value of bw_seq gets chosen by the function). Maybe this is just the result of our matching.

**Comment by wxwx1993** [comment]
@m-qin Also, you may also try [estimate_semipmetric_erf.R](https://github.com/fasrc/CausalGPS/blob/develop/R/estimate_semipmetric_erf.R), as the fully non-parametric models may be very flexible and influenced by outliers (if the outlier exists in the data).

**Comment by m-qin** [comment]
Thanks for these great suggestions @wxwx1993 ! I'll look into outliers at w_val = 5 in my pseudo-population and try `estimate_semipmetric`!

**Comment by Naeemkh** [comment]
@m-qin, please re-open this if it is still an issue. For scientific discussions, please open a discussion.
