### ISSUE TITLE
Suggestion: allow estimate_pmetric_erf() and estimate_semipmetric_erf() to take in more parameters for gam and gnm

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#154]
Editing my original post after reading `estimate_pmetric_erf.R` and `estimate_semipmetric_erf.R()`!

Hello! My outcome model needs to have an extra parameter (i.e., `offset = log(person_years)`) than the 4 parameters currently in estimate_pmetric_erf() and estimate_semipmetric_erf() (i.e., `formula, family, data, ci_appr`), so I am wondering if estimate_pmetric_erf() and estimate_semipmetric_erf() could be edited to take in more parameters than these 4?

Maybe one solution could be to have the user enter a list of named parameters instead of the specific parameters `formula, family, data, ci_appr`. Then, estimate_pmetric_erf() and estimate_semipmetric_erf() could run something like `do.call(gam, user_entered_list)`.

**Comment by daniellebraun** [comment]
@Naeemkh @wxwx1993

**Comment by Naeemkh** [comment]
Thanks, @m-qin, for the feature requests. Now both gam and gnm's optional arguments can be passed to semi-parametric and parametric approaches. The new implementation will be available at ver0.4.x.
