### ISSUE TITLE
Suggestion: Allow `estimate_npmetric_erf()` to take in GPS-weighted data

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#155]
Hello! I see in the documentation and code that `estimate_npmetric_erf()` is designed for GPS-matched data. However, I think it would also work for GPS-weighted data?

I used `estimate_npmetric_erf()` to plot my weighted data by scaling up and rounding my weights to integers, since `matched_counter` parameter must be an integer for the line `tidyr::uncount(data.frame(matched_Y), matched_counter)` in [estimate_npmetric_erf.R](https://github.com/fasrc/CausalGPS/blob/master/R/estimate_npmetric_erf.R) to work.

**Comment by wxwx1993** [comment]
Round weights to integers should practically work, though it is not very common in weighing literature.

**Comment by m-qin** [comment]
Gotcha, thanks @wxwx1993! Do you know if there's a more standard way to plot a nonparametric ERF for a GPS-weighted psuedopopulation? Would you recommend using KernSmooth::locpoly directly?

**Comment by daniellebraun** [comment]
@wxwx1993

**Comment by Naeemkh** [comment]
Has this issue been resolved?
