### ISSUE TITLE
Accept "SL.gam" as `sl_lib` and its parameters as `params`

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#165]
Hello! I would like to use the SuperLearner library "SL.gam" in `generate_pseudo_pop()`, but I need to add a custom parameter (`cts.num = 16`). I'm wondering if the CausalGPS package can be updated to allow this?

I see that `generate_pseudo_pop()` calls `estimate_gps()`, which calls `gen_wrap_sl_lib()`, which is defined in the _generate_wrap_sl_lib.R_ file and currently accepts parameters only for "SL.xgboost" (which the user enters as `sl_lib = "m_xgboost"`) and "SL.ranger" (which the user enters as `sl_lib = "m_ranger"`).

**Comment by Naeemkh** [comment]
For a short and quick workaround, you can redefine your function according to the following and use it in the `sl_lib` list.

```r
SL.gam_cts <- function(cts.num = 16, ...) SL.gam(cts.num = cts.num, ...)
```

However, a better solution is to develop a wrapper. You can read more about it here:
https://fasrc.github.io/CausalGPS/articles/Notes-on-SL-Wrapper.html

**Comment by m-qin** [comment]
Thanks so much Naeem!
