### ISSUE TITLE
Allow estimate_npmetric_erf to avoid uncount steps

### ISSUE THREAD

**Issue by wxwx1993** [NSAPH-Software/CausalGPS#166]
Load a new library

`library("locpol")
`
Change
`  erf <- stats::approx(KernSmooth::locpoly(matched_w, matched_Y, bandwidth=h_opt), xout=w_vals)$y
`
to
`erf <- locpol::locpol(formula = Y~w, data = data, bw = h_opt, weig = counter, xeval = a.w_vals, kernel = gaussK)`

This will allow us to avoid uncount steps in the function, and save memories. Also, it will make the non-parametric implementation more aligns with semi-/parametric implementations.

The function in https://github.com/fasrc/CausalGPS/blob/develop/R/smooth_erf.R will need to change accordingly as well.

**Comment by Naeemkh** [comment]
@wxwx1993,  thanks for the suggestion. However, it requires importing a new package. We try to avoid package dependency as much as possible. Although, with the new implementation, we can drop importing the `tidyr` package. I will consider adding it.

**Comment by Naeemkh** [comment]
I see. That is a valid point. I did catch it at first glance. I will double-check it.
