### ISSUE TITLE
NA's in output from `estimate_pmetric_erf()`

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#179]
When running `estimate_pmetric_erf()` on my dataset, I get the typical model summary outputs {Estimate, Std. Error, z value, Pr(>|z|)} when I enter the formula `Y ~ w`, but when I enter the formula `Y ~ w + confounder_1 + confounder_2 + … + confounder_n`, I get results for Estimate but NA’s for Std. Error, z value, and Pr(>|z|). Interestingly, no such NA’s occur when I use `glm()` instead of `estimate_pmetric_erf().` Has anyone else encountered this issue?

I am using gps matching and a logistic regression outcome model, so my code is:

```
# this does not work
outcome <- estimate_pmetric_erf(formula = Y ~ w + confounder_1 + confounder_2 + … + confounder_n,
                                  family = binomial,
                                  data = pseudo_pop,
                                  ci_appr = "matching")

# this also does not work
outcome <- estimate_pmetric_erf(formula = as.formula(paste(c("Y ~ w", confounders), sep = "", collapse = " + "),
                                  family = binomial,
                                  data = pseudo_pop,
                                  ci_appr = "matching")

# this works
outcome <- glm(formula = as.formula(paste(c("Y ~ w", confounders), sep = "", collapse = " + ")),
                 family = "binomial",
                 data = pseudo,
                 weight = counter_weight)
```

**Comment by Naeemkh** [comment]
Hi @m-qin, could you please post a reproducible example here. Thanks.

**Comment by Naeemkh** [comment]
@m-qin, closing this issue. If it is still an issue, please reopen the issue and add a reproducible example.
