### ISSUE TITLE
Add Kolmogorov-Smirnov (KS) statistics evaluation in generate_pseudo_pop function

### ISSUE THREAD

**Issue by wxwx1993** [NSAPH-Software/CausalGPS#185]
The sample code is like this

Note ks_statistics is only calculated for w and x, but not for Y
`library("Ecume")
`
`ks_stat <- sapply(2:(ncol(tmp_data)), function(i) ks_test((tmp_data[,i]), as.numeric(tmp_data[,i]), w_x = rep(1, nrow(tmp_data)), w_y = counter_weight)$statistic)
`
Report ks_stat, and its mean/max/median (similar as absolute correlation)

**Comment by Naeemkh** [comment]
@wxwx1993, do you need this for all iterations or for the latest generated pseudo population?
