### ISSUE TITLE
 get confidence interval  when use estimate_npmetric_erf

### ISSUE THREAD

**Issue by zhangc927** [NSAPH-Software/CausalGPS#191]
Thank you for this extraordinary work, after reading the paper carefully, feel benefited a lot. Sorry, there is a problem when I use estimate_npmetric_erf: I cannot get the confidence interval of the Exposure Response Curved point. I don't know if I didn't find it, please let me know when you are free.

Also, is a Python version of pycausalgps going to be released? Because I think python is more efficient with machine learning.

Thank you again for your work, and I intend to focus on this approach to the students.

**Comment by Naeemkh** [comment]
Hi @zhangc927, thanks for reaching out. `m-out-of-n Bootstrap Procedure` has yet to be implemented. The python package will be released soon. Thanks for your kind words.
