### ISSUE TITLE
suggest earth

### ISSUE THREAD

**Issue by pdbailey0** [NSAPH-Software/CausalGPS#192]
if you [have a test using the earth package](https://github.com/NSAPH-Software/CausalGPS/blob/master/tests/testthat/test-estimate_npmetric_erf.R#L41), I'd put `earth` in the [suggests](https://github.com/NSAPH-Software/CausalGPS/blob/master/DESCRIPTION#L51).

**Comment by Naeemkh** [comment]
Thanks, @pdbailey0, for bringing this to our attention. I added `earth` in the Suggests.
