### ISSUE TITLE
new version of wCorr changes Spearman results

### ISSUE THREAD

**Issue by pdbailey0** [NSAPH-Software/CausalGPS#193]
I'm releasing wCorr 2.0 soon and it causes a test regression in CausalGPS results. I'll submit a new version on March 14th--or earlier if CausalGPS gets updated on CRAN.

The issue is that the weighted Spearman was asymmetric about 0, so cor(x,y) != -cor(-x,y) 

In wCorr 2.0.9000 this is fixed with the formula in [this issue](https://github.com/ahmademad/wCorr/issues/62)

install instructions for 2.0.9000 on the [GitHub website](https://github.com/American-Institutes-for-Research/wCorr/).

[edited by PB to add link to wCorr GitHub, which is not the old GitHub where the issue is.]

**Comment by Naeemkh** [comment]
Hi @pdbailey0, thanks for the heads up. I will keep an eye on your release. Upon getting it out, I will review and modify the tests accordingly.

**Comment by pdbailey0** [comment]
@Naeemkh, I've contacted the CRAN maintainers to see what the best path is. Ideally, your next version would depend on wCorr having a version >= 2.0 so that users get the best results. until then, you can update it wCorr to the latest and fix the tests, skipping them if it's not the latest version
```
skip_if_oldwCorr <- function() {
  if(packageVersion("wCorr") >= "2.0.0") {
    return(invisible(TRUE))
  }
  skip("Please update wCorr to 2.0.0 to test")
}
```
Again, [wCorr github install link](https://github.com/American-Institutes-for-Research/wCorr/).

**Comment by Naeemkh** [comment]
Great. Thanks, @pdbailey0!

**Comment by Naeemkh** [comment]
Thanks, @pdbailey0. Yes, I will modify the code soon. Really appreciate the heads up.
