### ISSUE TITLE
In `compile_pseudo_pop`, does `delta_n` need to be specified if `bin_seq` is specified?

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#198]
Using the `compile_pseudo_pop` function, I am putting in a custom sequence of exposure bins (through the parameter `bin_seq`). The [CausalGPS documentation](https://cran.r-project.org/web/packages/CausalGPS/CausalGPS.pdf) says that in this case I do not need to enter a value for the `delta_n` parameter since it won't be used to define the exposure bins anyway. However, when I do not include a value for `delta_n` in my function call, I get the following error:

```
Error in check_args_compile_pseudo_pop(ci_appr = ci_appr, optimized_compile = optimized_compile,  : 
  At least one argument is not provided. Missing argument:  delta_n
```

The error appears to disappear if I write `delta_n = NULL` in the function call. I'll be able to confirm whether this works in a few hours; my code hasn't finished running yet (GPS matching).

**Comment by m-qin** [comment]
Update: Although no errors were printed on my console, it seems that matching did not work (with me inputting a custom `bin_seq` and `delta_n = NULL`). In the resulting pseudopopulation, `counterweight=0` for all units. The logger file, which I had set at the "TRACE" level, is blank.

**Comment by m-qin** [comment]
Actually, I think I should put in `delta_n = ` {some placeholder number, maybe -1} along with my custom `bin_seq`. I looked at https://github.com/NSAPH-Software/CausalGPS/blob/master/R/matching_l1.R and https://github.com/NSAPH-Software/CausalGPS/blob/master/R/create_matching.R, which are called by `compile_pseudo_pop`, and it seems like `delta_n` does need to be a number, so that the logger file can report "There is no data to match in... {delta_n} radius".

**Comment by Naeemkh** [comment]
Hi @m-qin, 
The `delta_n` parameter is the caliper size in the matching approach, and the user needs to provide it. In the current version, the package does not support variable caliper size based on variable bin_seq. So if you provide `bin_seq = [1, 2, 3, 9]`, and `delta_n = 0.5`, the subset of data will be generated according to the following brackets

(0.5,1.5)
(1.5,2.5)
(2.5,3.5)
(8.5, 9.5)

It can be a good feature to consider in the next version.

**Comment by m-qin** [comment]
Ah okay. Thanks for clarifying @Naeemkh!
