### ISSUE TITLE
change the argument "gps_model = parametric/non-parametric" to "gps_density = normal/kernel"

### ISSUE THREAD

**Issue by wxwx1993** [NSAPH-Software/CausalGPS#201]
The argument "gps_model" really means assuming the residual of the GPS density to be "normal" or using flexible kernel density estimates. Therefore, specifying "parametric" or "non-parametric" is not accurate.

```
  if (gps_model == "parametric"){
    p_w <- stats::dnorm(w, mean = e_gps_pred, sd = e_gps_std_pred)
  } else if (gps_model == "non-parametric") {
    w_new <- compute_resid(w, e_gps_pred, e_gps_std_pred)
    p_w <- compute_density(w_resid, w_new)
  }
```

@jennyjyounglee, how do you feel?

**Comment by jennyjyounglee** [comment]
I agree! As we discussed, how about gps_density = "normal"/"kernel" instead of gps_model = "parametric"/"non-parametric"?

**Comment by Naeemkh** [comment]
@wxwx1993, what do you think about @jennyjyounglee 's suggestion?
