### ISSUE TITLE
enable trimming by GPS in addition to or instead of trimming by exposure

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#202]
This is something I'm trying out with my ADRD project with Dan and Naeem. Trimming GPS is more justified in the literature than trimming exposure (even though they may be correlated sometimes, they are not the same). I've written my own code to do this, but it would be cool to see it as an option in CausalGPS in the future.

**Comment by Naeemkh** [comment]
@wxwx1993, do you have any comments to add to this issue?

**Comment by daniellebraun** [comment]
i agree with @m-qin

**Comment by wxwx1993** [comment]
I agree.

**Comment by Naeemkh** [comment]
Should we keep both of them? Trimming exposure level can be considered for positivity assumption. But as @m-qin, mentioned trimming GPS is more justified. Another option is leaving trimming exposure levels to the user and trim data based on GPS values.

**Comment by wxwx1993** [comment]
Keep both. For now, our algorithm indeed allows untriming of exposure, right?

**Comment by Naeemkh** [comment]
Yes. If we pass (0, 1) for trimming quantiles, it uses the entire data.
