### ISSUE TITLE
How does GPS matching handle ties between matches?

### ISSUE THREAD

**Issue by m-qin** [NSAPH-Software/CausalGPS#205]
### Discussed in https://github.com/NSAPH-Software/CausalGPS/discussions/204

<div type='discussions-op-text'>

<sup>Originally posted by **m-qin** March  5, 2023</sup>
During GPS matching, when several rows are tied for being the closest match to a desired template unit (because these rows have the same exposure and same covariates, so they have the same estimated GPS value), does the GPS matching algorithm deterministically select the first row? The answer to this question has implications on our ESS and number of observations matched (`sum(counter_weight > 0)`).

One might ask, why would your dataset contain rows with the same exposure and covariates but presumably different outcomes? This happens in my ADRD project with Dan and Naeem, where several patients live in the same ZIP code, so they have the same ZIP-level exposure and ZIP-level covariates (which go into the GPS model) but different outcomes and different individual-level covariates (which go into the outcome model but not the GPS model).</div>

**Comment by Naeemkh** [comment]
See the discussions at #204.
