### ISSUE TITLE
Add trim to weighting 

### ISSUE THREAD

**Issue by Naeemkh** [NSAPH-Software/CausalGPS#79]
We need to trim the large weights by setting all weights higher than that at a given quantile to the weight at the quantile (for weighting approach).

**Comment by wxwx1993** [comment]
Do we add this feature to the package? (https://github.com/fasrc/CausalGPS/blob/develop/R/create_weighting.R). It would be useful since otherwise it would be difficult for the weighting approach to achieve covariate balance.

**Comment by Naeemkh** [comment]
@wxwx1993, yes, we are planning on that. It seems we need to review the trimming process to make sure that the user is not confused. Do we trim data in the design stage, analyses stage, or both? And do we keep consistency in matching and weighting? These topics should be well-documented.
