### ISSUE TITLE
Add complete matched set to the output of generate_pseudo_pop function

### ISSUE THREAD

**Issue by wxwx1993** [NSAPH-Software/CausalGPS#88]
For output of the generate_pseudo_pop, add outputs of both the complete matched set and the trimmed matched set (e.g., trimmed out 1%/99%) (and called it trimmed_pseudo_pop). The current implementation only outputs a trimmed matched set.

I think even better, we should have an argument to allow user control whether output the complete matched set (as an optional choice)

**Comment by Naeemkh** [comment]
One can get the complete matched set with setting `trim_quantiles` = c(0.0,1.0). Does it help?

**Comment by wxwx1993** [comment]
Yeah, but I think it is still helpful to include the complete dataset in output even if not setting trim_quantiles = c(0.0,1.0), considering someone may prefer the "fit + trim" approach.
